language: node_js
node_js:
- '6'
install:
- yarn
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: heroku
  app: gc-node-chat
  api_key:
    secure: be51xZZGdrvCvW6lion074b7sMk+kpkYaPtV7gbhQLt64Ntml1bqD65rmgq3DgU7eZtvU4qy4SNXrebtpXg4gBag5EIvQopZbGEjlbOjeR1Z2gCYdhWPxh/wOmfvCusq/oPV2msCn8CmjsGIcy2Quk2xE63uP8XibflNT3mUnyl/MhhJtI3T/DdJNlGl942IP+8BZr7q0wz1xMVpEP/jdKs2eHocVLFwNq+x83P4b3yXUNmg5KpmaX45y8I/WlX+zEphDvbnb964rXo9YMPo04tn6jzP+RH+5D2PHQ4a2SGB3ygCBlN5hO9pvEqtmsRctZkUpkSE1hpN4Mm6qoNa8alFnUWKOJVb7nGQACAYmO5NnIfFkeEZe070GmAar4pO9j1jzkpiGQh5811PODgsZLC041BiIAzzHYiqDPg2Gl37ddJb9fzFuxzR5g67llrKRTTW2APSXOv5gn++D2jQD4yAxbMv9BoLrNsI7A5Gstlj/VXjoChT9lB+n4X3hYfGn0pWgmDukJqFK6vIR6kzIzJA2sUSxtaBRYWI2Z5x+Sf+/YmDtsYANM1X7RbXBGKkPtqPMNjcsfxzxeorNCW9igyQCAX9q+Fx5X0rl8ZQRNi6DoyPqY2p1C1oCyr+WlLsIxAp0pfKuXeQIucbVFv7Ak5kAjRaX2Redr7P7B8wMkA=
  on:
    branch: master
